// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRyFIt-itNWd5iRe8DNvA95ZTIvlttwo',
    appId: '1:363672644377:web:47c0dd62b9f0da4edd3388',
    messagingSenderId: '363672644377',
    projectId: 'chat-app-79bae',
    authDomain: 'chat-app-79bae.firebaseapp.com',
    storageBucket: 'chat-app-79bae.appspot.com',
    measurementId: 'G-JVVDXSF4MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwAOcmxUgN2EXioQmhV7qzT8GjK3_kjQ',
    appId: '1:363672644377:android:ea3950cfe78a65aedd3388',
    messagingSenderId: '363672644377',
    projectId: 'chat-app-79bae',
    storageBucket: 'chat-app-79bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8a93eeGDmFBOGTKUJESISdGDYWTh6mxo',
    appId: '1:363672644377:ios:94c868dee76f64dbdd3388',
    messagingSenderId: '363672644377',
    projectId: 'chat-app-79bae',
    storageBucket: 'chat-app-79bae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8a93eeGDmFBOGTKUJESISdGDYWTh6mxo',
    appId: '1:363672644377:ios:94c868dee76f64dbdd3388',
    messagingSenderId: '363672644377',
    projectId: 'chat-app-79bae',
    storageBucket: 'chat-app-79bae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATRyFIt-itNWd5iRe8DNvA95ZTIvlttwo',
    appId: '1:363672644377:web:2dcfcef4c57f4e56dd3388',
    messagingSenderId: '363672644377',
    projectId: 'chat-app-79bae',
    authDomain: 'chat-app-79bae.firebaseapp.com',
    storageBucket: 'chat-app-79bae.appspot.com',
    measurementId: 'G-Q61JS5HTDP',
  );
}
